name: "PacketStream"
slug: "packetstream"
description: "Earn passive income by sharing your unused bandwidth"
init: false
legacy: true
arch:
  - aarch64
  - amd64
  - i386
version: "latest"
image: packetstream/psclient
options:
  CID: "6eJ7"
schema:
  CID: str
